# Generated by Django 5.2.1 on 2025-08-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrawmaterial',
            old_name='material_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='productrawmaterial',
            old_name='material',
            new_name='raw_material',
        ),
        migrations.AlterUniqueTogether(
            name='productrawmaterial',
            unique_together={('product', 'raw_material')},
        ),
    ]
