# Generated by Django 5.2.4 on 2025-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
