# Generated by Django 5.2.4 on 2025-08-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_rawmaterial_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
