# Generated by Django 5.2.4 on 2025-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
