# Generated by Django 5.2.4 on 2025-11-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientosinventario'),
        ('inventory', '0002_rating'),
    ]

    operations = [
    ]
