# Generated by Django 5.2.1 on 2025-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productrawmaterial_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrawmaterial',
            name='minimum_stock',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='countrawmaterial',
            name='total_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='countrawmaterial',
            unique_together={('raw_material',)},
        ),
    ]
