# Generated by Django 5.2.4 on 2025-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_created_at_order_date_order_name_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
