# Generated by Django 5.2.4 on 2025-10-11 16:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_discount_total_order_subtotal_order_total_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.RenameField(
            model_name='productrawmaterial',
            old_name='material',
            new_name='raw_material',
        ),
        migrations.AlterUniqueTogether(
            name='productrawmaterial',
            unique_together={('product', 'raw_material')},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_order_total',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_qty',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='scope',
        ),
        migrations.AddField(
            model_name='productrawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Si es porcentaje, 10 = 10%; si es monto fijo, 10.00', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='productrawmaterial',
            name='material_quantity',
        ),
    ]
