# Generated by Django 5.2.1 on 2025-08-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_countrawmaterial_minimum_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrawmaterial',
            options={'verbose_name': 'Contador de Materia Prima', 'verbose_name_plural': 'Contadores de Materias Primas'},
        ),
        migrations.AlterUniqueTogether(
            name='countrawmaterial',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='countrawmaterial',
            name='minimum_stock',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='countrawmaterial',
            name='raw_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='inventory.rawmaterial'),
        ),
    ]
