# Generated by Django 5.2.4 on 2025-08-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_quantity_alter_product_picture_and_more'),
        ('inventory', '0002_product_stock'),
        ('inventory', '0008_rename_order_id_orderitem_order_and_more'),
    ]

    operations = [
    ]
