# Generated by Django 5.2.4 on 2025-08-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_countrawmaterial_options_and_more'),
        ('inventory', '0010_remove_product_stock_alter_product_quantity'),
    ]

    operations = [
    ]
