# Generated by Django 5.2.4 on 2025-09-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_order_customer'),
        ('inventory', '0010_remove_product_stock_alter_product_quantity'),
    ]

    operations = [
    ]
