# Generated by Django 5.2.4 on 2025-10-14 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('inventory', '0002_alter_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID for non-registered users', max_length=100, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser information')),
                ('customer', models.OneToOneField(blank=True, help_text='Customer who gave consent (if registered)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consent', to='inventory.customer')),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-date_accepted'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(help_text='Link to existing Customer model in inventory', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='inventory.customer')),
                ('user', models.OneToOneField(help_text='Django User for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True, help_text='True if list is editable, False if confirmed')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('week_number', models.IntegerField(help_text='Week number of the year this list was generated')),
                ('year', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='inventory.customer')),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'week_number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.PositiveIntegerField(help_text='Quantity suggested by the system based on purchase history')),
                ('user_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity modified by the user (optional)', null=True)),
                ('average_frequency', models.FloatField(default=0.0, help_text='How often this product is purchased (times per week)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping List Item',
                'verbose_name_plural': 'Shopping List Items',
                'unique_together': {('shopping_list', 'product')},
            },
        ),
    ]
